# Originally generated by nixos-generate-config and then refactored so
# every per-install value is sourced from vars.nix at the repo root.
{
  config,
  lib,
  modulesPath,
  host,
  ...
}:

assert lib.elem host.cpu.vendor [
  "amd"
  "intel"
];

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = host.initrdKernelModules;
      kernelModules = [ ];
    };
    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/${host.disks.root.uuid}";
      inherit (host.disks.root) fsType;
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/${host.disks.boot.uuid}";
      inherit (host.disks.boot) fsType options;
    };
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault host.system;
  hardware.cpu.${host.cpu.vendor}.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
